### ISSUE TITLE
Shift sending too many key events when pressed down w/ external keyboard

### ISSUE THREAD

**Issue by rosiaruuretto** [termux/termux-x11#130]
With input methods that switch on the key Shift, merely pressing down Shift causes input methods to switch. Upon examination with xev, it turns out that unlike other modifier keys such as Ctrl, holding down Shift sends a series of KeyRelease event as if Shift is some letter. Android 11 with physical keyboard although I believe the problem could be elsewhere too.

**Comment by zanfix** [comment]
I noticed this one too, android 10 with dex 2.5. it appears problematic for me only for Shift_L

I have a swiss keyboard, set as such in android and xfce

My workaround has been to:
- swap <TLDE> with <LSGT>, since for some reason <LSGT> acts as <AE12> (/usr/share/X11/xkb/symbols/ch)
  degree and section are accessible with AltGr on <AE04> and <AE05> respectively on this keyboard
- disable <LFSH> key (/usr/share/X11/xkb/symbols/pc)
- remap Shift_L to <AE12> (/usr/share/X11/xkb/symbols/ch)

This has the effect of having shift on <AE12> and <LSGT>. <LSGT> is on the right of <LFSH> on swiss keyboard.
i loose dead_circumflex and dead_grave on <AE12> but that does not bother me...

**Comment by twaik** [comment]
Can you please check if it happens with latest build [here](https://github.com/twaik/termux-x11/actions)?
