### ISSUE TITLE
can i render with gnome3？

### ISSUE THREAD

**Issue by susdevlop** [termux/termux-x11#175]
i want to render a gnome3 whit chroot container.     
can i use :     
env DISPLAY=:1 gnome3-session

**Comment by AlexBreedveld** [comment]
#45

**Comment by twaik** [comment]
You can try.

**Comment by twaik** [comment]
Did it work?

**Comment by AlexBreedveld** [comment]
I tried to use XFCE4 with Ubuntu on a chroot jail, but I wasn't able to get it working.
At the least I was able to find out what the problem is, which in my case was that the user id and group id for the Wayland socket wasn't accessible between Termux-x11 and XFCE4.

XFCE4 required the socket to be set as `root` , but then if you chmod it for that uid, the Termux-x11 app won't be able to read/write to the socket, thus failing to render the GUI.

I tried a bunch of ways to make the same socket accessible to both XFCE4 and Termux-x11, by trying bind-mount on chroot and via a rooted terminal on android, linking the file, changing the XDG runtime on Termux-x11 to another directory... But still wasn't able to get it working due to these permission issues.

Android uses a different user id and group id for each app (for security reasons), and this is what is causing the problem in this case.

Here's a visualization of the problem in question, `u_729` will be the Termux-x11 UID and GID used in this example:

| Socket  | User     | Group |  Problem   |
|--------------|-----------|------------|-------------|
| wayland-0.lock  |  root     | root        |  XFCE4 will be able to read/write to the socket, but Termux-x11 won't.  |
| wayland-0.lock  | u_729  | u_729    |  Termux-x11 will be able to read/write to the socket, but XFCE4 requires the socket to be both user and group set to `root`  |
