### ISSUE TITLE
Add full screen

### ISSUE THREAD

**Issue by Yisus7u7** [termux/termux-x11#29]
Please it would be nice if you added the full screen feature again, having the buttons and Android status bar in view makes me uncomfortable.

**Comment by RalfWerner** [comment]
### Fullscreen mode and Floating Termux, ExtraKey (EK) lack
On devices with a small screen and without Split/PiP capacity, the Fullscreen mode choice from Basic **X11** (@twaik) is helpful. Unfortunately, this was removed from the current version (Preferences). If it would be used _default_, that would be ok, but it is not. My Gigaset is such a device and expanded with [T:Float](https://github.com/termux/termux-float/issues/37#issue-986858850) and [Taskbar](https://github.com/termux/termux-x11/pull/19#issuecomment-908235805) App. So I reach a Split/PiP comparable behavior. Unfortunately, these Apps are poor. Here two shots on the topic that has been created with [OTS](https://github.com/termux/termux-float/issues/37#issuecomment-916777123):
![grafik](https://user-images.githubusercontent.com/45426380/132847218-0fc75f3f-8791-47c9-a872-083ccc61e212.png)
- shot1 **X11** as background in fullscreen mode with XClients: `fluxbox, check` and `touch`.
The X-Task/Window-Manager `fluxbox` is on botton.
**Taskbar** App (right above transparent priority to **X11**) is open. **Termux** could open here by _lon tap_ on Icon.
**Float** App is transparent in the middle with transparent and floating OS-KB next to it. The App can freely be scaled and moved with _long tap_ on the fullscreen. But in landscape maximum to the right as you see here (one of many bugs).
- shot2 after _long tap_ and select _floating_ **Termux** in shot1. The **Taskbar is reduced, the **X11** fullscreen mode is lost and OS-KB removed and Nav-Bars (red lines inside) are added. The configure event reduce the size of `fluxbox` (Taskbar still at bottom) and `check` (hight*0.6 here 16->12 lines).
With _tap_ on any point of **X11** or _long tap_ on **Float** fullscreen mode is back but **Termux** from **Taskbar** is removed. So parallel working with **X11** and **Taskbar** is _not really_ possible without permanently losing control of one of the two Apps. With **Float*, it is only limited because each _normal tap_ action switches off the fullscreen mode and OS-KB on and revers.

When the **Float** bugs (Fullscreen lost and missing EK, Session-list/`DRAWER` and Copy/Paste) are solved and the **Float** iconicization is used, this is a good solution for small phones. Especially, as Split has much more problems. In the current **X11** version, the NavBars can no longer be removed, the EK are displayed by preference (Bug switching is not correct) and the **X11** screen is reduced by the _non-floating_ OS-KB.
![grafik](https://user-images.githubusercontent.com/45426380/132847611-52d9ebfa-2b88-4a56-89f3-20c07f28ea38.png)
- shot1: In this case, only a very small **X11** screen remains after the Configure event, which is predominantly _not usable_ because of the EK transparent superimposed and this is also superimposed by **Float** and this from OS-KB, so that no _"viewable"_ inputs can take place.
- shot2: shows the screen after rotation to portrait position and iconicization of **Float**. Here everything could be entered except "5" in `check` and EK handling differs to landscape position.

**Comment by RalfWerner** [comment]
@suhan-paradkar @twaik @agnostic-apollo Is one of you busy with the **restoration/implementation?** If so, a few notes:
Full screen Mode (FM) in Init-**X11** had also runtime bugs on _some_ AVD emulators but [not here](https://github.com/termux/termux-x11/pull/19#issuecomment-924812641). It's ok if the two NavBars are [briefly](https://user-images.githubusercontent.com/45426380/133095986-50fcd2b4-8b2a-4e33-97e7-1977a5197522.png) displayed with sweep from the edge and than disappear again. This creates _no configure_ events.

The calculation of the "used area" for **Termux** and **X11** is apparently not trivial. So the addition of the NavBars at FM and the subtraction of _non-floating_ KB`*)` in the two phone positions must be considered. Since this leads to different effects on different devices, it's to check on all. _Floating_ KB do not affects it.
`*)` KB=Key-Board as EK+OS=Extra-Keys + On-Screen

If two or more apps are on the screen (PiP, Split) remain the NavBars I suspect if one of the apps they use. Therefore, **Termux** should also be FM-able to do so as soon as possible.

EK could also be moved as a floating box on the screen when it is not multiple and different. Since OS-KB toggles with `KEYBOARD` EK is possible, the Back key is no longer needed at **X11** and could receive its _nominal determination._

**Comment by Yisus7u7** [comment]
> ### Fullscreen mode and Floating Termux, ExtraKey (EK) lack
> On devices with a small screen and without Split/PiP capacity, the Fullscreen mode choice from Basic **X11** (@twaik) is helpful. Unfortunately, this was removed from the current version (Preferences). If it would be used _default_, that would be ok, but it is not. My Gigaset is such a device and expanded with [T:Float](https://github.com/termux/termux-float/issues/37#issue-986858850) and [Taskbar](https://github.com/termux/termux-x11/pull/19#issuecomment-908235805) App. So I reach a Split/PiP comparable behavior. Unfortunately, these Apps are poor. Here two shots on the topic that has been created with [OTS](https://github.com/termux/termux-float/issues/37#issuecomment-916777123): ![grafik](https://user-images.githubusercontent.com/45426380/132847218-0fc75f3f-8791-47c9-a872-083ccc61e212.png)
> 
> * shot1 **X11** as background in fullscreen mode with XClients: `fluxbox, check` and `touch`.
>   The X-Task/Window-Manager `fluxbox` is on botton.
>   **Taskbar** App (right above transparent priority to **X11**) is open. **Termux** could open here by _long tap_ on Icon.
>   **Float** App is transparent in the middle with transparent and floating OS-KB next to it. The App can freely be scaled and moved with _long tap_ on the fullscreen. But in landscape maximum to the right as you see here (one of many bugs).
> * shot2 after _long tap_ and select _floating_ **Termux** in shot1. The **Taskbar** is reduced, the **X11** fullscreen mode is lost and OS-KB removed and Nav-Bars (red lines inside) are added. The configure event reduce the size of `fluxbox` (Taskbar still at bottom) and `check` (hight*0.6 here 16->12 lines).
>   With _tap_ on any point of **X11** or _long tap_ on **Float** fullscreen mode is back but **Termux** from **Taskbar** is removed. So parallel working with **X11** and **Taskbar** is  possible without permanently losing control of one of the two Apps. With **Float**, it is only limited because each _normal tap_ action switches off the fullscreen mode and OS-KB on and revers.
> 
> When the **Float** bugs (Fullscreen lost and missing EK, Session-list/`DRAWER` and Copy/Paste) are solved and the **Float** iconicization is used, this is a good solution for small phones. Especially, as Split has much more problems. In the current **X11** version, the NavBars can no longer be removed, the EK are displayed by preference (Bug switching is not correct) and the **X11** screen is reduced by the _non-floating_ OS-KB. ![grafik](https://user-images.githubusercontent.com/45426380/132847611-52d9ebfa-2b88-4a56-89f3-20c07f28ea38.png)
> 
> * shot1: In this case, only a very small **X11** screen remains after the Configure event, which is predominantly _not usable_ because of the EK transparent superimposed and this is also superimposed by **Float** and this from OS-KB, so that no _"viewable"_ inputs can take place.
> * shot2: shows the screen after rotation to portrait position and iconicization of **Float**. Here everything could be entered except "5" in `check` and EK handling differs to landscape position. Unlike landscape, EK is positioned here under **X11** and not over it as in shot1.

It just doesn't work properly, there's a blank space left.

**Comment by RalfWerner** [comment]
@Yisus7u7 Your [commit](https://github.com/termux/termux-x11/issues/29#issuecomment-931298857) above I do not understand! If it is contentless, delete it easily.

**Comment by twaik** [comment]
Fixed by 9de5f2f0deca3f057d429843d8e3e04d88bdfa98 .
