### ISSUE TITLE
drawbacks of legacy mode

### ISSUE THREAD

**Issue by arenddeboer** [termux/termux-x11#489]
This is more a discussion than a bug report, but didn't see a way to create a new discussion.
I'm enjoying termux-x11 with xfce on my Samsung S22 Ultra. To get past the black screen, I had to use the `-legacy-drawing` mode. I wonder if this is because of the Exynos chip in my European S22. Am I missing out with this legacy mode ? Text seems to be a bit aliased. 
Looking forward to get audio and two way copy paste working (but that might not be possible I've read)

**Comment by twaik** [comment]
> I wonder if this is because of the Exynos chip in my European S22.

That is because your device does not support drawing a AHardwareBuffer-backed BGRA texture. I did not found any way to fix this other then using old, less optimized drawing method (uploading texture and drawing it instead of zero-copy drawing in newer method).

> Text seems to be a bit aliased.

That may be because of wrong resolution. Try to use `native` or `scaled` resotution mode.

> Looking forward to get audio

It should work out-of-the box if you are using Xfce. Not sure about other DEs. In the case if there is still no sound you should start `pulseaudio` daemon manually. Termux:X11 is a X server, it is not responsible for audio support.

> two way copy paste working (but that might not be possible I've read)

Correct.

**Comment by arenddeboer** [comment]
Thanks for the quick response. Got audio working and a bit more insight into the other issues.
