### ISSUE TITLE
[Bug]: Termux-x11 freezes 

### ISSUE THREAD

**Issue by jamesgarry1** [termux/termux-x11#516]
### Problem description

Android: 10
Termux: 0.118.0
Termux-x11: 1.03.00
Termux-x11 is a wonderful project and there is one thing that pisses me off
After 7 seconds termux-x11 freezes and unfreezes when i press the circle on my phone bar/close the keyboard and freezes again 

### What steps will reproduce the bug?

I dont know how to reproduce the bug it happens randomly
In the past I removed contents of /tmp/ and it got fixed
This time i tried to remove the contents of /tmp/ it didn't work

**Comment by RalfWerner** [comment]
> _"one thing that pisses me off"_ and _"I dont know how to reproduce the bug it happens randomly"_

The developer cannot find a solution with this information. Try to find a repeatable scene, describe it and enter your device type and manufacturer.

**Comment by jamesgarry1** [comment]
Manufacturer is huawei
Device is P40 Lite

**Comment by twaik** [comment]
Try `-legacy-drawing` option, I hope it will help.

**Comment by RalfWerner** [comment]
I had a similar problem with my Huawei Y7 3-4 years ago, that I tried to solve with @twaik for several months. At that time I called it **SSM** = _"Stupid Stalled Mode"_, which never occurred when I had connected a power cable (very stupid).
The problem could not be repeated on my other devices (non Huawei) and @twaik had no such device, so that we gave up after a half year. There are no problems with the `Xvnc` Server. Maybe that's an alternative for you, when it not solved by `-legacy-drawing`.

**Comment by twaik** [comment]
> I had a similar problem with my Huawei Y7 3-4 years ago

Irrelevant, new version uses different technology.

**Comment by RalfWerner** [comment]
> Irrelevant, new version uses different technology.

I will check that - thanks for the hint :)

**Comment by jamesgarry1** [comment]
`-legacy-drawing` Does not fix the problem

**Comment by jamesgarry1** [comment]
I will try to clear the cache of both apps

**Comment by jamesgarry1** [comment]
Clearing cache was the solution

**Comment by jamesgarry1** [comment]
Nevermind, after clearing the cache it didn't resolve the issue

**Comment by twaik** [comment]
Try to disable battery restrictions for both apps.

**Comment by jamesgarry1** [comment]
I fixed the problem the problem was i didnt put termux in the background

**Comment by RalfWerner** [comment]
> termux in the background

What does it mean - both App has to be aktiv?

**Comment by RalfWerner** [comment]
As [promised](https://github.com/termux/termux-x11/issues/516#issuecomment-1855462561), my Huawei Check: My **SSM** [Problem](https://github.com/termux/termux-x11/issues/516#issuecomment-1855454024) above **_also exists_** with the _current X11 version_. I rarely use them because it does not use reasonable _gesture control_ as with **ekeys** and there are other problems. For example, **fluxbox** does'nt work in _direct mode_. Nothing is displayed on the Huawei _without_ `-legacy-drawing`, but with all my other devices and when the power cable is connected, the work can be continued, but I will switch back to **ekeys**, because it is much easier to use.

I do not provide screenshots because you don't have an appropriate device.

**Comment by jamesgarry1** [comment]
By the way this was a duplicate to #501 and i cannot seem to use termux-x11 without it freezing even with legacy drawing

**Comment by jamesgarry1** [comment]
The solution in the 501th issue seem to fix the issue

**Comment by twaik** [comment]
Is this issue still reproducible witth latest build? Without `-legacy-drawing` flag.

**Comment by jamesgarry1** [comment]
Yeah i think its because of low battery mode but i dont care about termux x11 anymore because i got a IOS

**Comment by ImNotTheChiku35** [comment]
Turn on "Allow background activity" for Termux? it work for me

**Comment by twaik** [comment]
Closing in prior to termux/termux-app#3903
