### ISSUE TITLE
[Bug]: Wrong touching position

### ISSUE THREAD

**Issue by numberokta** [termux/termux-x11#569]
### Problem description

When touchMode is Simulated touchscreen and Reseed is true and soft keyboard is open, makes touching in wrong position

### What steps will reproduce the bug?

touchmode='Simulated touchscreen'
Reseed=true
open soft keyboard
touching the screen simulates touching in the wrong position

### What is the expected behavior?

I think touching display size does not change when soft keyboard is opened and display scale is changed and it must be fix

**Comment by twaik** [comment]
I can not reproduce this. Can you record your screen with `show taps` and `pointer location` toggles active?
<details>

![image](https://github.com/termux/termux-x11/assets/9674930/f36fe884-fab8-4ecd-bad3-eec53daa7a18)
</details>

**Comment by numberokta** [comment]
you first must open soft keyboard and then run
```
PATH=/data/data/com.termux/files/usr/bin termux-am broadcast --user 0 -a com.termux.x11.CHANGE_PREFERENCE -p com.termux.x11 -e touchMode 'Simulated touchscreen'
```
from terminal in termux-x11 while soft keyboard is open. now close soft keyboard and touch somewhere

https://github.com/termux/termux-x11/assets/20727200/7552ab09-3dde-4757-b6c4-e11458a0ef49

**Comment by RalfWerner** [comment]
@numberokta  The gestures in your video are either **1.** `tap+release` or **2.** `tab+move+release`. However since **1.03.00, 2.** has only been possible as: `long-tap+move+release` and `long` about a second, in which the finger is not allowed to move, otherwise the whole gesture will be ignored. The **pointer** (arrow in your video), would also be moved to the **finger position.** if `long-tab` is valid.

This actually has nothing to do with `On Screen KB` and it can also be repeated without XClient. The only way to avoid it, is use of `1.02.06`, if you like this `touchMode`. I ask @twaik at least four times to change the behavior but he threatened me with ban when I continue (#533).
So I continue to use `1.02.06`, which also has further improvements, although the current version also has great advantages like `CHANGE_PREFERENCE`, which allows setup inside XClient.

**Comment by numberokta** [comment]
It's not long tap release, it's tap release and it just get wrong touching position because of changing display scale after closing soft keyboard. the new version is so much better and have more feature and still under developing.

**Comment by RalfWerner** [comment]
Could you check again that **not** `Trackpad` was used in your video (`list`)? The gesture **1.** is identical in both modes, always work correctly and often occurs in your video. Pay attention to the red line (`move`) in your video. The gestures without line correspond to **1.** Typical for `Trackpad` is the parallel movement of the pointer to the red line.
The pointer is only arrow in the upper window and changed in the lower. A **1. gesture** `tap+release` is always necessary as a conclusion but **not** in `Simulated touchscreen`. I'll prepare a Video with both Modes and without XClient and extend it in this commit, when it's done
> I can not reproduce this. Can you record your screen with ... (@twaik)

The Developer Option `Pointer location` is corresponding to `Direct touch` in all three `touchModes`, even if XServer only `this` supports generic events. This in turn is only supported by a few XClients.
The option is limited to 7 fingers, although I could also support more than 10. This depends on devices and I don't have so many fingers but it is only possible if this Development Options are switched off.

I sometimes use the XClient **fluxbox** as a Windows Manager if other XClient like **xterm** cannot analyze the display configuration. Unfortunately, **fluxbox** does not work well with `Direct touch`.

**Comment by twaik** [comment]
> I ask @twaik at least four times to change the behavior but he threatened me with ban when I continue (#533).

Again. It is behaviour of project I ported. Changing it breaks other gestures in this mode. End of story.

> The Developer Option `Pointer location` is corresponding to `Direct touch` in all three `touchModes`

It is Android option. Not option of TX11. 

> even if XServer only `this` supports generic events.

Maybe this sentence has some sense for German native speaker, but I do not understand it.

> if other XClient like **xterm** cannot analyze the display configuration

It is not a bug. Xterm creates **window** and that is a reason it requires **window manager**. Like most of X11 applications.

**Comment by numberokta** [comment]
First i show that in `Trackpad` mode everything's ok and then execute command to change `touchMode` to `Simulated touchscreen` and then tap on screen while soft keyboard is open, then i close soft keyboard and tap on screen and as you can see touch point and cursor position is not same

**Comment by RalfWerner** [comment]
The [Video:53](https://github.com/termux/termux-x11/assets/45426380/288eb1e4-7a47-42b8-bb8c-9ba18a008425) [above](https://github.com/termux/termux-x11/issues/569#issuecomment-1970904345) shows the `Simulated touchscreen` in the first 20 seconds and `Trackpad` from 0:23. In both sequences, Termux and X11 are displayed. X11 App shows **fluxbox** with a window that only processes _generic events_ (Direct) and does _nothing_ here. The window is maximized, normalized/smaller and moved in both modes one time.
The `long-tab` gesture **2.** in `Tackpad mode` is also necessary when moving window.
> ... Changing it breaks other gestures in this mode.

If I had an impact on `long-tab`, that would be an alternative for _"normal app behavior"_ e.g. 1 instead of 1000ms
> Maybe `this` sentence ...  I do not understand it.

`this` refers to _generic events!_ **clear now?**
> It is not a bug. Xterm creates window and that is a reason it requires window manager. Like most of X11 applications.

Right, like "most of X11 apps" but **not* like _"most of Android Apps"._ I working on XClient with Android behavior and Version 1.02.06 allows it. With just a few exceptions, Termux have also **normal android behavior!**
`xterm`, could get by with a little effort work without **WM**.

**Comment by numberokta** [comment]
You're wrong, first 20 seconds is Trackpad and after that is Simulated touchscreen. I don't know why you insist so much in the beginning of the video, the touch mode is Simulated touchscreen. I think I explained enough, you're just saying something irrelevant to this issue.

**Comment by RalfWerner** [comment]
> You're wrong, first 20 seconds is Trackpad and after that is Simulated touchscreen.

![image](https://github.com/termux/termux-x11/assets/45426380/ff4275aa-13a4-4c20-8543-32d2f39f80c0)
Left is Termux and right is X11. with `x list` the current settings are listet (In shot marked). Here with **OS_KB**=On-Screen-KB. The difference in behavior I expect since 2019 and is equal in Version 1.02.06 but without delay of `long-tab`.

Additional you see **EK**=Extra-Keys (twice in both Apps) and Hacker-KB in the shot. In both KB could switch on/off by **EK**

**Comment by RalfWerner** [comment]
> Stop Mentioning Behavior of 2019 version. Enough. (@twaik)

1.02.06 (**ekeys**) is from Jul 2022! 2019 was your first X11 app publication with the same three `touch modes`. In between there are many improvements primarily by @suhan-paradkar #19 done, some of them are now also available in 1.03.00.

I've **accepted** your decision for `long-tap` gestures some weeks ago!, You can obviously **not reset** them, but asked whether the _time limit_ for `long` can be changed. Unfortunately, you deleted the question with all other commits and did **not answer.** There is no _time limit_ necessary for `Direct touch`.

Incidentally, my contributions in this issue were mainly directed to @numberokta.

**Comment by RalfWerner** [comment]
@numberokta I studied again the gestures in your [video](https://github.com/termux/termux-x11/issues/569#issuecomment-1969463381): Between second 20 and 22, `touchMode` was switched to `Simulated touchscreen`. From then on, _only_ `tap+release` are done with one exception between the seconds **27-28.** The `tap+move+release` would be invalid but is not done in X11 but on the Android NAV-button `End` (`<`), which switches the OS-KB on/off. For a valid `long-tap+move+release` gesture you need a little more patience - [see my](https://github.com/termux/termux-x11/assets/45426380/288eb1e4-7a47-42b8-bb8c-9ba18a008425).

**Comment by ewt45** [comment]
I can reproduce this when display resolution mode=custom/exact and touchscreen input mode=simulated touchscreen.
when toggling soft input, somehow `LorieView.mSurfaceCallback.surfaceChanged()` is not called at all. So the transformation is not updated.
The only difference I can tell is that 
- custom/exact resolution mode: the LorieView is scaled with a fixed aspect ratio 
- native/scaled resolution mode: the LorieView always tries to strench to fit the screen, so the aspect ratio is changed

maybe it's better to call LorieView.triggerCallback() manually when toggling soft input?

**Comment by RalfWerner** [comment]
> I can reproduce this when ... touchscreen input mode=simulated touchscreen.

@ewt45 What can you reproduce? The faulty **gesture** `tab+move+release`? I also checked the `exact` and found no difference to `scaled`. My problem is that this **gesture** is always ignored. @twaik said `long+tap` was necessary because this is typical **gesture** of Android/Google/Chrome. I cannot confirm that. With [debug](https://github.com/termux/termux-x11/assets/45426380/c6e85532-19f5-4fed-852d-51da92315b07) I've checked the apps: [chrome](https://github.com/termux/termux-x11/assets/45426380/d7a1ca96-1f72-40f0-9e5d-c989420fceda), [maps](https://github.com/termux/termux-x11/assets/45426380/96bce50d-3116-4877-a145-5c898f7f4265) and [photo](https://github.com/termux/termux-x11/assets/45426380/e37bd06a-0f5e-48df-8862-a5dfece0253d) and all three do the same as [ekeys](https://github.com/termux/termux-x11/issues/569#issuecomment-1971671433)

**Comment by twaik** [comment]
> The faulty **gesture** `tab+move+release`?

No. The faulty gesture is another one. The one described in the first message.


> this is typical **gesture** of Android/Google/Chrome

No. Of Chrome Remote Desktop. Completely different product.

And this time I am banning you. You were warned about `tab+move+release`. Multiple times.

**Comment by RalfWerner** [comment]
> And this time I am banning you.

Why ban? I had [granted](https://github.com/termux/termux-x11/issues/569#issuecomment-1971671433) you to keep the **lost gestures.** But on your hint, I checked again [RD](https://github.com/termux/termux-x11/assets/45426380/1bee68a4-435b-4615-b787-54245870781a)=Remote Desktop with my Windows desktop. There are no **lost gestures** and **RD** do what expect (scroll up/down), in the last two touch modes. The first two modes work similarly to X11. However, **RD** has problems with XServers on Windows and fails. Is not an issue here!

**Comment by twaik** [comment]
Newer version is not Java-based. It is some kind of web-app. I used old java version. And again, it is off-topic.

**Comment by RalfWerner** [comment]
Topic is: _"Wrong touching position"_! When a gesture is lost, I _expect_ the pointer in the wrong position.

**Comment by twaik** [comment]
Again. The topic is "Wrong touching position" and topicstarter described it pretty clear: when he uses specific touch modes and toggles keyboard position of cursor is **wrong**. **No lost gestures.** Another user even found the reason of this: `LorieView.mSurfaceCallback.surfaceChanged()` is not called because surface size was not changed. 
Next time you post off-topic message it will be deleted immediately. Older off-topic messages will be deleted immediately too.

**Comment by twaik** [comment]
@numberokta @ewt45 can you please test the latest build on https://github.com/termux/termux-x11/actions/runs/8223825785 ?

**Comment by numberokta** [comment]
@twaik thanks

**Comment by ewt45** [comment]
> @numberokta @ewt45 can you please test the latest build on https://github.com/termux/termux-x11/actions/runs/8223825785 ?

yes, it works correctly now

**Comment by RalfWerner** [comment]
@numberokta  I probably understood where your problem was. You only made **gesture1** before and after OS-KB _"on/off"_. The **gesture2** for _"on/off"_ (NAV bar) is not X11. OS-KB leads to a _"re-configuration"_ of the screen and between _"on"_ and _"off"_ you have changed the touchMode. I extracted the [7 seconds](https://github.com/termux/termux-x11/assets/45426380/f23d982d-7a3c-4def-bc2a-e4d6f0e2bb51) after that. You have made one **gesture1** before _"Off"_ and three after _"Off."_ Better now?!

I also installed @twaiks Update and [checked](https://github.com/termux/termux-x11/assets/45426380/57439d13-6489-4d58-9193-9da5ea091019), where the pointer is located before/after the _"re-Configuration"_ and OS-KB by KB-key _"on/off"_. In between made three **gesture1** that is ok:) The pointer position according to _"on/off"_ seems randomly. In the **ekeys** version, the pointer is still at the same position after the _"re-configuration"_ as before.
