### ISSUE TITLE
[Bug]: Forking to my app

### ISSUE THREAD

**Issue by epicstudios856** [termux/termux-x11#579]
### Problem description

i have using 
        CmdEntryPoint.main(new String[]{":0"});

and i get this error

(the fork is merged with the app to load proot instead of termux app)

### What steps will reproduce the bug?

        CmdEntryPoint.main(new String[]{":0"});

### What is the expected behavior?

2024-03-13 22:33:02.714 16627-16627 LorieNative             com.vectras.vm                       V  Using TMPDIR="/data/data/com.vectras.vm/files/usr/tmp"
2024-03-13 22:33:02.716 16627-16661 gles-renderer           com.vectras.vm                       D  Xlorie: Initialized EGL version 1.5
2024-03-13 22:33:02.718 16627-16662 CmdEntryPoint           com.vectras.vm                       E  Listening port 7892
2024-03-13 22:33:02.718 16627-16661 hw-ProcessState         com.vectras.vm                       D  Binder ioctl to enable oneway spam detection failed: Invalid argument
2024-03-13 22:33:02.731 16627-16661 gles-renderer           com.vectras.vm                       E  There is no current context, `renderer_set_buffer` call is cancelled
2024-03-13 22:33:02.735 16627-16661 LorieNative             com.vectras.vm                       E  Failed to activate virtual core keyboard: -1590199840
---------------------------- PROCESS ENDED (16627) for package com.vectras.vm ----------------------------
2024-03-13 22:33:02.735 16627-16661 LorieNative             com.vectras.vm                       E  Server stopped (1)

**Comment by twaik** [comment]
Do you have xkeyboard-config in your prefix?

**Comment by epicstudios856** [comment]
nope

how i can add it in proot alpine
can u explain it to me please

**Comment by twaik** [comment]
That is not a bug. And I am not interested in explaining such things. In the case if you want to create your VM app you should know how to configure its parts.

**Comment by epicstudios856** [comment]
it not work too bruh
   apk add xkeyboard-config

**Comment by twaik** [comment]
Probably this package has another name. Search by contents. 
You can use https://github.com/termux/termux-packages/blob/master/x11-packages/xkeyboard-config/build.sh to get more details about this package in termux.

**Comment by epicstudios856** [comment]
u mean i need to build it by myself to set xkb path?

**Comment by twaik** [comment]
Probably you forgot to export `XKB_CONFIG_ROOT`.

**Comment by epicstudios856** [comment]
thanks for help bro it fixed now

**Comment by twaik** [comment]
Probably you are doing something wrong...

**Comment by epicstudios856** [comment]
this code is correct?
        CmdEntryPoint.main(new String[]{":0"});

**Comment by epicstudios856** [comment]
?

**Comment by epicstudios856** [comment]
i will be clear
i have checked CmdEntryPoint.java
and it seems loading external app
and i want to load internally with the app what the code i must use to load ur app internally in my app?

**Comment by epicstudios856** [comment]
there is way to start xserver from ur display manager?

**Comment by epicstudios856** [comment]
x11 not loaded btw in MainActivity

xhost:  unable to open display ":0"

**Comment by epicstudios856** [comment]
what is this "XKB_CONFIG_ROOT"
and where i can find it in alpine instead of termux

**Comment by twaik** [comment]
> there is way to start xserver from ur display manager?

Display manager must be started after X server. There is `-xstartup` option. It is stated in `Readme.md`

> i have checked CmdEntryPoint.java and it seems loading external app 
and i want to load internally with the app what the code i must use to load ur app internally in my app?

It is not loading external app. It is loading JNI code.
It was not designed to work in the same process as MainActivity. It was designed to work in another process, in different Android application sandbox, establishing connection through sockets, Binder+AIDL and some private Android APIs. 

> x11 not loaded btw in MainActivity

Of course it is not. Because MainActivity is pretty much dumb client needed to get Surface and user input from Android and send it to X server. It does not contain any X server logic.

> another error lol

I'm not going to help with every single step you do or every single mistake you are getting while debugging.
Termux:X11 is a pretty big project, containing parts of code from Xwayland, Xvfb, TigerVNC, Chrome Remote Desktop, other applications, some code from random repos of github and gitlab, some pieces I wrote on my own after digging https://cs.android.com/ and https://gitlab.freedesktop.org/ or even torturing ChatGPT (which was pretty much useless btw). It was a long way. There were a lot of stuff I dropped (like implementing minimal viable wayland compositor for Xwayland, using libxcb to make Termux:X11 some kind of screen capturer for Xvfb, etc). And I am not going to explain every single step I did to Termux:X11 to make it work. And I am not intending to explain you pretty much basic things like usage of `&` and where exactly it is handled (**NOT** in Termux:X11).

**Comment by twaik** [comment]
That is not a bug or even issue. In the case you want to get help there is Discord server (link is in `Readme.md`) which has `coding` channel.
