### ISSUE TITLE
[feature request] wayland compositors support (hyprland, sway)

### ISSUE THREAD

**Issue by gmankab** [termux/termux-x11#596]
hello

can you please add support for wayland compositors, like hyprland and sway

**Comment by twaik** [comment]
No.

**Comment by TomJo2000** [comment]
To give a more detail explanation.
Termux:X11 is not a Wayland compositor, and as such cannot, and will not support Wayland desktops.

You can use the currently offered Wayland Desktops, (Weston, Sway, LabWC<sub>[[work in progress]](https://github.com/termux/termux-packages/pull/19587)</sub>) through either RDP, Waypipe or WayVNC.
Although WayVNC is Wlroots specific, so that won't work for Weston.

**Comment by twaik** [comment]
There is a more simple reason. Termux:X11 is X server and Wayland is out of its scope.

**Comment by gmankab** [comment]
> You can use the currently offered Wayland Desktops, (Weston, Sway, LabWC[[work in progress]](https://github.com/termux/termux-packages/pull/19587)) through either RDP, Waypipe or WayVNC

thanks
